version: "3.9"

services:
  server_dev:
    build: ./server
    command: python manage.py runserver 0.0.0.0:5257
    volumes:
      - ./server/:/usr/src/app/
    ports:
      - 5257:5257
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
    ports:
      - 5432:5432

  redis_dev:
    container_name: redis_dev
    image: redis:7-alpine

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    user: root
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    env_file:
      - ./.env.prod
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
